# Generated by Django 2.2.4 on 2020-02-22 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
    ]
